[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ChemInterface_ppchem"
version = "1.0"
description = "..."
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
keywords = ["unsaturation", "Mass spectroscopy"]
authors = [
  { name = "Thomas Christianson", email = "thomas.christiansson@epfl.ch" },
  { name = "Igor Gonteri", email = "igor.gonteri@epfl.ch" },
  { name = "Arthur Humery", email = "arthur.humery@epfl.ch" }
]
dependencies = [
  "bzip2=1.0.8",
  "ca-certificates=2024.3.11",
  "libffi=3.4.4",
  - openssl=3.0.13=h2bbff1b_1
  - pip=23.3.1=py310haa95532_0
  - python=3.10.12=he1021f5_0
  - setuptools=68.2.2=py310haa95532_0
  - sqlite=3.45.3=h2bbff1b_0
  - tk=8.6.12=h2bbff1b_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.41.2=py310haa95532_0
  - xz=5.4.6=h8cc25b3_1
  - zlib=1.2.13=h8cc25b3_1
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]

[project.urls]
Homepage = "https://github.com/ThomasCsson/ppchem-project-Christiansson-Gonteri-Humery.git"