[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
dynamic = ["version"]
name = "ChemInterface_ppchem"
version = "1.0"
description = "..."
readme = {file = "README.txt", content-type = "text/markdown"}
requires-python = ">=3.8"
license = "MIT"
keywords == [
  "unsaturation", 
  "Mass spectroscopy"
  ]
authors = [
  {name = "Thomas Christianson", email = "thomas.christiansson@epfl.ch"},
  {name = "Igor Gonteri", email = "igor.gonteri@epfl.ch"},
  {name = "Arthur Humery", email = "arthur.humery@epfl.ch"}
  ] 

dependencies = [
  "blas==1.0=mkl",
  "bzip2==1.0.8=h2bbff1b_5",
  "ca-certificates==2024.3.11=haa95532_0",
  "intel-openmp==2023.1.0=h59b6b97_46320",
  "libffi==3.4.4=hd77b12b_0",
  "mkl==2023.1.0=h6b88ed4_46358",
  "mkl-service==2.4.0=py310h2bbff1b_1",
  "mkl_fft==1.3.8=py310h2bbff1b_0",
  "mkl_random==1.2.4=py310h59b6b97_0",
  "numpy==1.26.4=py310h055cbcc_0",
  "numpy-base==1.26.4=py310h65a83cf_0",
  "openssl==3.0.13=h2bbff1b_0",
  "pip==23.3.1=py310haa95532_0",
  "python==3.10.12=he1021f5_0",
  "setuptools==68.2.2=py310haa95532_0",
  "sqlite==3.41.2=h2bbff1b_0",
  "tbb==2021.8.0=h59b6b97_0",
  "tk==8.6.12=h2bbff1b_0",
  "vc==14.2=h21ff451_1",
  "vs2015_runtime==14.27.29016=h5e58377_2",
  "wheel==0.41.2=py310haa95532_0",
  "xz==5.4.6=h8cc25b3_0",
  "zlib==1.2.13=h8cc25b3_0"
  ]

license = {file = "LICENSE"}
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"]

[project.urls]
Homepage = "https://github.com/ThomasCsson/ppchem-project-Christiansson-Gonteri-Humery.git"
