[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = ""
version = ""
description = ""
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
keywords = []
authors = [
  { name = "Thomas Christianson", email = "" },
  { name = "Igor Gonteri", email = "" }
  { name = "Arthur Humery", email = "arthur.humery@epfl.ch"}
  ]
dependencies = [] 