[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ChemInterface_ppchem"
version = "1.0"
description = "..."
readme = {file = "README.txt", content-type = "text/markdown"}
requires-python = ">=3.8"
license = "MIT"
keywords = ["unsaturation", "Mass spectroscopy"]
authors = [
  { name = "Thomas Christianson", email = "thomas.christiansson@epfl.ch" },
  { name = "Igor Gonteri", email = "igor.gonteri@epfl.ch" },
  { name = "Arthur Humery", email = "arthur.humery@epfl.ch" }
]
dependencies = [
  "blas==1.0",
  "bzip2==1.0.8",
  "ca-certificates==2024.3.11",
  "intel-openmp==2023.1.0",
  "libffi==3.4.4",
  "mkl==2023.1.0",
  "mkl-service==2.4.0",
  "mkl_fft==1.3.8",
  "mkl_random==1.2.4",
  "numpy==1.26.4",
  "numpy-base==1.26.4",
  "openssl==3.0.13",
  "pip==23.3.1",
  "python==3.10.12",
  "setuptools==68.2.2",
  "sqlite==3.41.2",
  "tbb==2021.8.0",
  "tk==8.6.12",
  "vc==14.2",
  "vs2015_runtime==14.27.29016",
  "wheel==0.41.2",
  "xz==5.4.6",
  "zlib==1.2.13"
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]

[project.urls]
Homepage = "https://github.com/ThomasCsson/ppchem-project-Christiansson-Gonteri-Humery.git"
